-- phpMyAdmin SQL Dump
-- version 4.0.4.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 02, 2013 at 08:20 AM
-- Server version: 5.5.32
-- PHP Version: 5.4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `dynasties`
--
CREATE DATABASE IF NOT EXISTS `dynasties` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `dynasties`;

-- --------------------------------------------------------

--
-- Table structure for table `ghazni`
--

CREATE TABLE IF NOT EXISTS `ghazni` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `ghazni`
--

INSERT INTO `ghazni` (`id`, `ruler`, `des`) VALUES
(1, 'Mahmud of Ghazni', 'In 971 CE, Yamin ad-Dawlah Abdul-Qasim Mahmud ibn Sabuktegin, better known as Mahmud of Ghazni, was born in the town of Ghazna, now in south-east Afghanistan. The baby''s father, Abu Mansur Sabuktegin, was Turkic, a former Mamluk warrior-slave from Ghazni.\r\n\r\nWhen the Samanid dynasty, based in Bukhara (now in Uzbekistan) began to crumble, Sabuktegin seized control of his home town of Ghazni in 977. He then went on to conquer other major Afghan cities, such as Kandahar. His kingdom formed the core of the Ghaznavid Empire, and he is credited with founding the dynasty. \r\n\r\nNot much is known about Mahmud of Ghazni''s childhood. We know that he had two younger brothers, and that the second one, Ismail, was born to Sabuktegin''s principal wife. The fact that she, unlike Mahmud''s mother, was a free-born woman of noble blood would turn out to be key in the question of succession when Sabuktegin died during a military campaign in 997.\r\nOn his deathbed, Sabuktegin passed over his militarily and diplomatically skilled eldest son Mahmud, 27 years old, in favor of the second son, Ismail. It seems likely that he chose Ismail because he was not descended from slaves on both sides, unlike the elder and younger brothers.\r\n\r\nIn 1026, the 55-year-old sultan set out to invade the state of Kathiawar, on India''s west (Arabian Sea) coast. His army drove as far south as Somnath, famous for its beautiful temple to the lord Shiva.\r\nAlthough Mahmud''s troops successfully captured Somnath, looting and destroying the temple, there was troubling news from Afghanistan. A number of other Turkic tribes had risen up to challenge Ghaznavid rule, including the Seljuk Turks, who had already captured Merv (Turkmenistan) and Nishapur (Iran). These challengers had already begun to nibble away at the edges of the Ghaznavid Empire by the time Mahmud died on April 30, 1030. The sultan was just 59 years old.\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `ghori`
--

CREATE TABLE IF NOT EXISTS `ghori` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `ghori`
--

INSERT INTO `ghori` (`id`, `ruler`, `des`) VALUES
(1, 'Muhammad of Ghor', 'Sultan ShahAb-ud-Din Muhammad Ghori (also spelled Ghauri, Ghouri), originally called Muizzuddin MuHammad Bin Sam (and also referred to by Orientalists as Muhammad of Ghor and famously known as just Ghori) (1150 to March 15, 1206), was one of the rulers of the Ghurid dynasty from the famous house of Sur who were rulers of Ghor for five hundred years. He is credited with laying the foundation of Islamic occupation in India that lasted for several centuries. He reigned over a territory spanning present-day Afghanistan, Pakistan and northern India.\r\n\r\nMuiz-ud-din, son of Sam Suri, nicknamed Shahab-ud-din which means The (Flashing) Fire of Religion (Islam) took the city of Ghazni in 1173 to avenge the death of his ancestor Muhammad Suri at the hands of Mahmud of Ghazni and used it as a launching-pad for expansion into northern India.In the meantime, he assisted his brother Ghiyasuddin in his contest with the Khwarezmid Empire for the lordship of Khorasan in Western Asia. In 1175 Ghori captured Multan from the Hamid Ludi dynasty which was also Pashtun but were alleged to be un-Islamic on the account of their association with Ismailite Shi iate sect and also took Uch in 1175. He also annexed the Ghaznavid principality of Lahore in 1186, the last haven of his Afghan but Non-Pashtun Persianized rivals. After the death of Ghiyasuddin in 1202, he became the successor of the Ghurid Empire and ruled until his assassination in 1206 near Jhelum in modern-day Pakista\r\n\r\n\r\nIn 1206, Shahabuddin Ghori had to travel to Lahore to crush a revolt. On his way back to Ghazni, his caravan rested at Damik near Sohawa (which is near the city of Jhelum in the Punjab province of modern-day Pakistan). He was assassinated on March 15, 1206, while offering his evening prayers. The identity of Shahabuddin Ghori''s assassins is disputed, with some claiming that he was assassinated by local Gakhars and others claiming he was assassinated by Khokhars Hindu.\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `gupta`
--

CREATE TABLE IF NOT EXISTS `gupta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Dumping data for table `gupta`
--

INSERT INTO `gupta` (`id`, `ruler`, `des`) VALUES
(1, 'Sri Gupta', 'Sri Gupta (240 to 280) was a pre-imperial Gupta king in northern India and start of the Gupta dynasty. A portion of northern or central Bengal might have been the home of Guptas at that time, but however not much evidence is available.\r\n\r\nThe first evidence of Sri Gupta comes from the writings of I-tsing around 690 CE who describes that the Poona copper inscription of Prabhavati Gupta, a daughter of Chandra Gupta, describes "Maharaja Sri-Gupta" as the founder of the Gupta dynasty. According to I-tsing''s account, Sri Gupta ordered the construction of a temple at Mrgasikhavana for the use of Buddhist pilgrims coming from China,endowing it with the revenue from 40 villages\r\n\r\nHistorian A. K. Narain (1983) noted that contemporary scholarship is unaware of Sri Gupta''s religious affiliation, due to the lack of surviving evidence. Narain suggested that because he constructed a temple for Chinese Buddhist pilgrims, Sri Gupta himself was follower of the Hindu sect of Vaisnavism who was tolerant of Buddhist activity in his kingdom\r\n'),
(2, 'Chandragupta I', 'Chandra Gupta was son of Ghatotkacha to the throne of the ancestral Gupta kingdom. While his two ancestors were given the title of Maharaja (king), Chandragupta I is described in his inscriptions as Maharajadhiraj (king of kings) signifying a rise in the family fortunes. \r\n\r\nHe gained control over many territories by conquests and favourable marriage alliances. He married a Lichchhavi princess to enhance his prestige.\r\n\r\nAfter 500 years of invasion and turmoil after Ashoka''s death, a strong leader named Chandragupta took over. Chandragupta married a daughter of a royal influential family. After marrying, he earned the title of Great King of Kings\r\n\r\nthe Gupta era began on the occasion of the coronation of Chandragupta I. According to the Puranas the Guptas ruled over territories (referred to as Janapadas) such as Prayag (Allahabad), Saket (Oudh) and Magadh (south Bihar). This description of the Gupta dominion precedes the reign of Samudragupta and hence must 	refer to the territories ruled over by Chandragupta I.\r\n'),
(3, 'Samudragupta', 'Samudragupta, ruler of the Gupta Empire (c. 335 to c. 375 CE), and successor to Chandragupta I, is considered to be one of the greatest military geniuses in Indian history. He was the third ruler of the Gupta Dynasty, who ushered in the Golden Age of India. He was perhaps the greatest king of Gupta dynasty.\r\n\r\nSamudragupta started to rule the kingdom and did not rest until he conquered almost the whole of India. His reigning period may be described as a vast military campaign. To begin with he attacked the neighboring kingdoms of Ahichchhatra (Rohilkhand) and Padmavati (in Central India). He conquered the whole of Bengal, some Kingdoms in Nepal and he made Assam pay him tribute\r\n\r\nHe absorbed some tribal states like the Malvas, the Yaudheyas, the Arjunayanas, the Abhiras and the Maduras. The rulers of Afghanistan, Central Asia and Eastern Iran Kushanas and the Sakas were made his tributaries.\r\n\r\nMuch is known about Samudragupta through coins issued by him and inscriptions. These were of eight different types and all made of pure gold. His conquests brought him the gold and also the coin-making expertise from his acquaintance with the Kushana. Most certainly, Samudragupta is the father of Gupta monetary system. He started minting different types of coins. They are known as the Standard Type, the Archer Type, the Battle Axe Type, the Ashvamedha Type, the Tiger Slayer Type, the King and Queen Type and the Lyre Player Type. They exhibit a fine quality of technical and sculptural finesse\r\n'),
(4, 'kumaragupta', 'Kumaragupta I (Mahendraditya) was a ruler of the Gupta Empire in 415 to 455 CE. Like his father and predecessor, Chandragupta II, Kumaragupta was an able ruler. He retained, intact, the vast empire, which extended from Bengal to Kathiawar and from the Himalayas to the Narmada. He ruled efficiently for nearly forty years. However, the last days of his reign were not good\r\n\r\nKumaragupta erected an iron pillar, today visible at the Qutb complex. The iron pillar is one of the world''s foremost metallurgical curiosities. The pillar was originally located in the temple of Muttra, with the deity Garuda at the top. It is the only piece of the Hindu temple remaining, which stood there before being destroyed by Qutb-ud-din Aybak to build the Qutub Minar and Quwwat-ul-Islam mosque. Qutub built around it when he constructed the mosque.\r\n\r\nInscriptions prove that the Gupta sovereignty was acknowledged in the Jabbalpur region in the Narmada valley as late as AD 528, and in North Bengal till AD 543 to 544. Kumaragupta II is believed to have been ruling in AD 473 to 474, Buddhagupta from AD 476 to 495, Vainyagupta in AD 508 and Bhanugupta in AD 510 to 511. The Gupta empire began to disintegrate and till the middle of the sixth century AD, they had merely became petty chiefs.\r\n\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `khilji`
--

CREATE TABLE IF NOT EXISTS `khilji` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data for table `khilji`
--

INSERT INTO `khilji` (`id`, `ruler`, `des`) VALUES
(1, 'Jalal ud din Firuz Khilji', 'Jalaluddin Khilji (died 20 July 1296) was the first sultan of the Khilji dynasty, who reigned from 1290 to 1296. He built his capital at Kilughari, a few miles from the city of Delhi and completed the unfinished palace and gardens of Sultan Qaiqabad.He ruled from there for six years i.e.(1290-1296)\r\n\r\nJalaluddin Khalji original name is Malik Firuz.He was appointed by Sultan Qaiqabad to the fief of Baran and the command of the army. Soon, Sultan Qaiqabad suffered from a paralytic stroke and Firuz marched towards Delhi. The nobles placed Kayumars, the three-year-old son of Qaiqabad on the throne. But the sons of Firuz dashed into the city and carried away the infant Sultan, defeating a force sent in pursuit of them. Most of the Turkic nobles now submitted to Firuz. Qaiqabad was put to death and his corpse was thrown into the Yamuna. On 13 July 1290 Jalal-ud-Din Firuz was enthroned in the palace of Kalughari.He was made a slave from there\r\n\r\nIn 1292, a horde of more than 100,000 Mongols invaded India. Successes in battle and smart negotiation caused a partial retreat on the part of the Mongols. They rose again five years later when his nephew and son-in-law Ala ud din Khilji was on the throne.\r\n\r\nAla-ud-din was also responsible for a successful raid in to Deccan as Governor of Kara under his uncle, Jalal-ud-din. Jalal-ud-din was killed by his cruel nephew Ali Gurshap when he arrived to dinner with him at kara\r\n'),
(2, 'Alauddin Khilji', 'Juna Khan Khilji,commonly known by his title as Ala-ud-din Khilji (died 1316), was the second ruler of the Turko-Afghan Khilji dynasty in India. He is considered the most powerful ruler of the dynasty,reigning from 1296 to 1316\r\n\r\nHis historic attack on Chittor in 1303 CE to capture the beautiful queen of Chittor, Rani Padmini, the wife of King Rawal Ratan Singh and the subsequent story have been immortalized in the epic poem Padmavat, written by Malik Muhammad Jayasi in the Awadhi language in the year 1540\r\n\r\nHe was a brilliant strategist and an outstanding military commander who commanded forces across the Indian subcontinent. Sultan Ala-ud-din Khilji is also noted in history for being one of the few rulers in the world to have repeatedly defended his empire against Mongol invasions. He defeated large Mongol armies and then launched punitive expeditions against them in Central Asia, around modern-day Afghanistan\r\n\r\nAlauddin Khilji successfully defended his realm from the Mongol invasion. He improved the border''s fortifications and established garrisons. He defeated the Mongol armies at the battles of Jalandhar (1298), Kili (1299), Amroha (1305) and Ravi (1306)\r\n'),
(3, 'Qutb ud din Mubarak Shah', 'Qutb-ud-din Mubarak Shah Khilji (died 1320) was the third and last ruler of the Khilji dynasty in Sultanate of Delhi, India. Qutb-ud-din Khilji was the son and successor of Alauddin Khilji.\r\n\r\nQutb-ud-din, at the age of 18, was originally appointed regent to his younger six-year old brother, the king. Within two months, Qutb-ud-din blinded his brother and ascended the throne. He began his rule by releasing thousands of prisoners and abolishing all taxes and penalties imposed by his father. Qutb-ud-din was the weakest ruler of the dynasty.\r\n\r\nQutb-ud-din was murdered by Khusro Khan in 1320, which ended the Khilji dynasty. Khusro Khan was a former Hindu slave of the Bawariya Hindu caste in Gujarat.	\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `lodi`
--

CREATE TABLE IF NOT EXISTS `lodi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data for table `lodi`
--

INSERT INTO `lodi` (`id`, `ruler`, `des`) VALUES
(1, 'Bahlol Lodi', 'Bahlul Khan Lodi (died July 1489) was the founder of Lodi dynasty of the Delhi Sultanate in India upon the abdication of the last claimant from the previous Sayyid rule. He was born into an Afghan family of traders, and became a renowned warrior and governor of Sirhind (Punjab). Bahlul became sultan of the dynasty on 19 April 1451 (855 AH)\r\n\r\nBahlul belonged to the Shahu Khel clan of the Lodi Pashtun tribe. Bahlul''s grandfather, Malik Bahram, settled in Multan during the reign of Firuz Shah Tughluq and took service under the governor of Multan, Malik Mardan Daulat. Malik Bahram had a total of about five sons. His eldest son, Malik Sultan Shah Lodi, later served under the Sayyid dynasty ruler Khizr Khan and distinguished himself by killing in the battle later''s worst enemy Mallu Iqbal Khan. He was rewarded with the title of Islam Khan and in 1419 appointed the governor of Sirhind. Bahlul, the son of Malik Kala, the younger brother of Malik Sultan was married to Malik Sultan''s daughter.\r\n\r\nBahlul died in July 1489 after a long reign. His tomb is a drab place compared to other mausoleums. It is a square chamber with three arched openings on all sides, surmounted by five domes, the central one being the biggest. Koranic verses are inscribed on the arches but there is hardly any other ornamentation.\r\n'),
(2, 'Sikander Lodi', 'Sikandar Lodi (died November 21, 1517), born Nizam Khan, was the Sultan of Delhi between 1489 to 1517. He became the next ruler of the Lodi dynasty after the death of his father Bahlul Khan in July 1489. He was also a poet of the Persian language and prepared a diwan of 9000 verses.\r\n\r\nSikandar proved to be a capable ruler who was kind to his Muslim subjects, but was extremely harsh to his Hindu subjects. He expanded Lodi territory into the regions of Gwalior and Bihar. He made a treaty with Alauddin Hussain Shah and his kingdom of Bengal. He was able to bring his native Afghan nobles under his control, and encouraged trade across his holdings. In 1503, he commissioned the building of the present-day city of Agra.\r\n\r\nSikandar Lodi tried to conquer the Gwalior Fort, and he attacked 5 times,but was failed all the five times by the king of Gwalior Maharaja Mansingh. He developed Agra as his second capital (after Delhi), as it took a lot of time to travel from Delhi to Gwalior. Agra eas known as Shiraz of India during Sikandar Lodi''s time.Finally he attacked a small region, near Gwalior named Narwar, and he had to wait 11 months at the gates of the Narwar fort, after 11 months when the people found that nothing had left to eat, they surrendered to Sikandar lodi. Once again he attacked on Gwalior, and was defeated by Maharaja Mansingh and his wife Mrignayani\r\n\r\nHe died in 1517 and has an elaborate burial tomb that resides in Lodi Gardens, Delhi.\r\n'),
(3, 'Ibrahim Lodi', 'Ibrahim Lodi (born April 21, 1526) was the Sultan of Delhi in 1526 after the death of his father Sikandar. He became the last ruler of the Lodi dynasty, reigning for nine years between 1517 until being defeated and killed by Babur''s invading army in 1526\r\n\r\nIbrahim was an ethnic Afghan through his father''s side. He attained the throne upon the death of his father, Sikandar, but was not blessed with the same ruling capability. He faced a number of rebellions. The Mewar ruler Rana Sangram Singh extended his empire right up to western Uttar Pradesh and threatened to attack Agra. There was rebellion in the East also. Ibrahim Lodi also displeased the nobility when he replaced old and senior commanders by younger ones who were loyal to him. He was feared and loathed by his subjects. His Afghan nobility eventually invited Babur to invade India.\r\n\r\nIn 1866, the British relocated the tomb during construction of the Grand Trunk Road and renovated it with an inscription highlighting Ibrahim Lodhi''s death in the Battle of Panipat.\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `marathas`
--

CREATE TABLE IF NOT EXISTS `marathas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--
-- Dumping data for table `marathas`
--

INSERT INTO `marathas` (`id`, `ruler`, `des`) VALUES
(1, 'Shahji Bhonsle', 'Shahaji Raje Bhosale  was a Maratha general from the 17th Century. He was an early exponent of guerilla warfare. He was the eldest son of Maloji Bhosale of Verul (present-day Ellora, Maharashtra). He brought the house of Bhosle into prominence. The princely states of Tanjore, Kolhapur and Satara are Bhosale legacies.\r\n\r\nThe Bhonsle family of the Poona district acquired military and political advantage in the Ahmadnagar kingdom at the close of the 16th century. Shahji Bhonsle was married to Jija Bai. He sought fortune under the Sultan of Bijapur and had his Jagir at Poona\r\n\r\nShahaji had two sons by Jijabai, Sambhaji and Shivaji. Sambhaji was killed while on a military expedition in Karnataka.He was cremated in town of channagiri taluk of Davanagere district of karnataka. Shahaji had one son Venkoji(Ekoji I) by his second wife, who came from the Mohite family. Venkoji later ruled over the independent Maratha kingdom of Thanjavur. Shahaji groomed all his sons as good administrators and men of culture and taste, Shivaji in the Pune region, Sambhaji in Banglore, and Venkoji in Thanjavur region\r\n	'),
(2, 'Shivaji', 'Shivaji was the son of Shahji Bhonsle. When he was 14 years old, his father entrusted the administration of the Pune Jagir to him. Shivaji''s responded to the aspiration of masses. Shivaji realised that he could establish a welfare state for the benefit of his subjects only by controlling the neighbouring forts and building new ones. \r\n\r\nShivaji showed his mettle at the young age of 18, when he overrun a number of hill forts near Poona- Rajgarh, Kondana and Torana during 1645-1647. Shivaji became his real career of conquest in 1656, when he conquered Javli from the Maratha Chief, Chandra Rao More. The Mughal invasion of Bijapur in 1657 saved Shivaji from the latter''s reprisal.\r\n\r\nShivaji visit to Agra: Shivaji reached Agra in 1666, and was admitted in the hall of public audience. The emperor gave him a cold reception by making him stand among the mansabdars. A humiliated and angry Shivaji walked out of the court. He, along with his son, was put under house arrest. However, they tricked their guards and managed to escape in a basket of sweets which was to be sent as a gift to the consolidating his position and reorganising his administration, Shivaji renewed his was against the Mughals and gradully recovered many of his forts. \r\n'),
(3, 'Balaji Viswanath\r\n', 'He began his career as a small revenue official and was given the title of Sena Karte (maker of the Army) by Shahu 1708. He became Peshwa in 1730 and made the post of most important and powerful as well as hereditary. He played a crucial role in the final victory of Shahu over the Mughuls by winning over almost all the Marathas Sardas to the side of Shahu. He concluded an agreement with the Sayyid brothers (1719) by which the Mogul emperor recognised Shahu as the king of the Swarajya .\r\n'),
(4, 'Baji Rao', 'Baji Rao, the eldest son of Balaji Viswanath, became Pashwa at the yound age of 20. He was considered the greatest exponent of gurrilla tactic after Shivaji and Maratha Power reached zenith under him. Baji Rao I conquered Bassein and Salsette from the Portuguese (1733). He also defeated the Nizar-ul-Mulk near Bhopal and concluded the Treaty of Durai Sarai by which he got Malwa and Bundelkhand from the latter (1737). He led innumerable successful expeditions into North India to weaken the Mughal empire and to make the Marathas the supreme power in India. He said "Let us strike at the trunk of the withering tree and the branches will fall of themselves.\r\n'),
(5, 'Balaji Baji Rao', 'Balaji Baji Rao Known as Nana Saheb, he succeeded his father at the age of 20. After the death of Sahu (1749), the management of all state of affairs was left in his hands. In an agreement with the Mughul emperor, the Peshwa (1752) was to protect the Mughal empire from internal and external enemies in return for the Chauth. \r\n\r\nThird Battle of Panipat: Faught in 1761, the Maratha forces were routed by the forces of Ahmad Shah Abdali. Vishwas Rao, son of Nana Saheb, lost his life. 	\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `maurya`
--

CREATE TABLE IF NOT EXISTS `maurya` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Dumping data for table `maurya`
--

INSERT INTO `maurya` (`id`, `ruler`, `des`) VALUES
(1, 'Chandragupta Maurya', 'Chandragupta Maurya (340 BC to 298 BC) was the founder of the Mauryan Empire and the first emperor to unify India into one state. He ruled from 322 BC until his voluntary retirement and abdication in favour of his son Bindusara in 298 BC.\r\n\r\nChandragupta Maurya is a pivotal figure in the history of India. Prior to his consolidation of power, most of South Asia was ruled by small states, while the Nanda Dynasty dominated the Gangetic Plains.Chandragupta succeeded in conquering and subjugating almost all of the Indian subcontinent by the end of his reign\r\n\r\nHis empire extended from Bengal and Assam in the east, to Afghanistan and Balochistan, eastern and south-east Iran in the west, to Kashmir in the north, and to the Deccan Plateau in the south. It was the largest empire yet seen in Indian history\r\n\r\nChandragupta gave up his throne in the beginning of 3rd century BCE, when he was forty-two years old, and became an ascetic under the Jain saint Bhadrabahu, migratiSng south with them and ending his days in sallekhana (death by fasting) at ravana Belgola in present day Karnataka.\r\n	'),
(2, 'Bindusara', 'Bindusara Maurya (c. 320 BC to 272 BC) was emperor of the Maurya Empire from 298 BC to 272 BC. During his reign, the empire expanded southwards. He had two well-known sons, Susima and Ashoka, who were the viceroys of Takshashila and Ujjain.\r\n\r\nBindusara was the son of the first Mauryan Emperor Chandragupta Maurya and his Empress consort, Durdhara. According to the Rajavalikatha a Jain work, the original name of this emperor was Simhasena\r\n\r\nBindusara, just 22 year old, inherited a large empire that consisted of what is now, Northern, Central and Eastern parts of India along with parts of Afghanistan and Baluchistan. Bindusara extended this empire to the southern part of India, as far as what is now known as Karnataka. He brought sixteen states under the Mauryan Empire and thus conquered almost all of the Indian peninsula (he is said to have conquered the ''land between the two seas'' - the peninsular region between the Bay of Bengal and the Arabian Sea).\r\n\r\nBindusara''s death in 272 B.C\r\n'),
(3, 'Ashoka the Great', 'Ashoka Maurya (304 to 232 BCE) commonly known Ashoka and also as Ashoka the Great, was an Indian emperor of the Maurya Dynasty who ruled almost all of the Indian subcontinent from ca. 269 BCE to 232 BCE.One of India''s greatest emperors, Ashoka reigned over most of present-day India after a number of military conquests\r\n\r\nHis empire stretched from the parts of the ancient territories of Khorasan, Sistan and Balochistan (unpartitioned) in what is now Afghanistan and possibly eastern Iran, through the Hindu Kush mountains in Afghanistan, to present-day Bangladesh and the Indian state of Assam in the east, and as far south as northern Kerala and Andhra Pradesh. The empire had Taxila, Ujjain and Pataliputra as its capital.\r\n\r\nAshoka is referred to as Samraat Chakravartin Ashoka the "Emperor of Emperors Ashoka." His name "asoka" means "painless, without sorrow" in Sanskrit (the a privativum and soka "pain, distress")\r\n\r\nAshoka ruled for an estimated forty years. After his death, the Mauryan dynasty lasted just fifty more years until his empire stretched over almost all of the Indian subcontinent. Ashoka had many wives and children, but many of their names are lost to time. His supreme consort and first wife was Vidisha Mahadevi Shakyakumari Asandhimitra. Mahindra and Sanghamitra were twins born by her, in the city of Ujjain.\r\n\r\nKing Ashoka, the third monarch of the Indian Mauryan dynasty, has come to be regarded as one of the most exemplary rulers in world history\r\n'),
(4, 'Dasaratha', 'Dasaratha (252 to 224 BCE) was Mauryan Emperor from 232 to 224 BCE. He was a grandson of Ashoka and had succeeded his grandfather as the imperial ruler of India. Dasaratha presided over a declining imperium and several territories of the empire broke away from central rule during his reign. He had continued the religious and social policies of his celebrated grandfather Ashoka\r\n\r\nDasaratha was the last ruler of the Mauryan dynasty to have issued imperial inscriptions thus the last Mauryan Emperor to be known from epigraphical sources.\r\n\r\nDasaratha is known to have dedicated three caves in the Nagarjuni Hills to the Ajivikas. Three inscriptions at the cave refer to him as "Devanampiya Dasaratha" and state that the caves were dedicated by him shortly after his accession\r\n\r\nDasaratha died in 224 BCE and was succeeded by his probable son or brother Samprati.Samprati, who succeeded Dasaratha, was according to the Hindu Puranas,the latter''s son and according to the Buddhist and Jain sources,Kunala''s son (making him possibly a brother of Dasaratha). The familial relationship between the two is thus not clear although evidently they were closely related members of the imperial family\r\n			');

-- --------------------------------------------------------

--
-- Table structure for table `mughal`
--

CREATE TABLE IF NOT EXISTS `mughal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=7 ;

--
-- Dumping data for table `mughal`
--

INSERT INTO `mughal` (`id`, `ruler`, `des`) VALUES
(1, 'Babar', '\r\nZahir-ud-din Muhammad Babur (14 February 1483 to 26 December 1530, sometimes also spelt Baber or Babar) was a conqueror from Central Asia who, following a series of setbacks, finally succeeded in laying the basis for the Mughal dynasty in the Indian Subcontinent and became the first Mughal emperor. He was a direct descendant of Timur, from the Barlas clan, through his father, and a descendant also of Genghis Khan through his mother.\r\n\r\nWhile Persian sources claim that Babur was influenced by the Persian culture and gave rise to the expansion of the Persianate ethos in the Indian subcontinent,other sources hold that he mostly contributed to the growth of the Turkic culture. Although all applications of modern Central Asian ethnonyms to people of Babur''s time are anachronistic, Soviet and Uzbek sources regard Babur as an ethnic Uzbek.\r\n\r\nBabur claimed to be the true and rightful Monarch of the lands of the Lodi dynasty. He believed himself the rightful heir to the throne of Timur, and it was Timur who had originally left Khizr Khan in charge of his vassal in the Punjab, who became the leader, or Sultan, of the Delhi Sultanate, founding the Sayyid dynasty. The Sayyid dynasty, however, had been ousted by Ibrahim Lodi, a Ghilzai Afghan, and Babur wanted it returned to the Timurids. Indeed, while actively building up the troop numbers for an invasion of the Punjab he sent a request to Ibrahim,"I sent him a goshawk and asked for the countries which from old had depended on the Turk," the ''countries'' referred to were the lands of the Delhi Sultanate.\r\n\r\nBabur died at the age of 47 on January 5 [26 December 1530] 1531, and was succeeded by his eldest son, Humayun. Though he wished to be buried in his favourite garden in Kabul, a city he had always loved, he was first buried in a mausoleum in the capital city of Agra.His remains were later moved to Bagh-e Babur (Babur Gardens) in Kabul, Afghanistan. \r\n'),
(2, 'Humayun', '\r\nNasir ud-din Muhammad Humayun (OS 7 March 1508 AD to OS 17 January 1556 AD) was the second Mughal Emperor who ruled a large territory consisting of what is now Afghanistan, Pakistan, and parts of northern India from 1530 to 1540 and again from 1555 to 1556. Like his father, Babur, he lost his kingdom early, but with Persian aid, he eventually regained an even larger one\r\n\r\nHumayun lost Mughal territories to the Pashtun noble, Sher Shah Suri, and, with Persian aid, regained them 15 years later.  The Central Asian origins of the dynasty were largely overshadowed by the influences of Persian art, architecture, language and literature. There are many stone carvings and thousands of Persian manuscripts in India from the time of Humayun.\r\n\r\nSher Shah Suri had died in 1545 his son and successor Islam Shah died too, in 1554. These two deaths left the dynasty reeling and disintegrating. Three rivals for the throne all marched on Delhi, while in many cities leaders tried to stake a claim for independence. This was a perfect opportunity for the Mughals to march back to India.The Mughal Emperor \r\n\r\nOn 27 January 1556, Humayun, with his arms full of books, was descending the staircase from his library when the muezzin announced the Adhan (the call to prayer). It was his habit, wherever he heard the summons, to bow his knee in holy reverence. Kneeling, he caught his foot in his robe but some say that he was pushed while he was trying to do that, tumbled down several steps and hit his temple on a rugged stone edge. He died three days later. They say ''he tumbled in life and finally tumbled out of it too''. His body was laid to rest in Purana Quila initially, however, because of attack by Hindu king Hemu on Delhi and capture of Purana Qila, Humanyun''s body was exhumed by fleeing army and transferred to Kalanaur in Punjab where Akbar was coronated.\r\n'),
(3, 'Akbar', 'Akbar (14 October 1542 to 27 October 1605), known as Akbar the Great, was Mughal Emperor from 1556 until his death. He was the third and greatest ruler of the Mughal Dynasty in India. Akbar succeeded his father, Humayun, under a regent, Bairam Khan, who helped the young emperor expand and consolidate Mughal domains in India\r\n\r\nA strong personality and a successful general, Akbar gradually enlarged the Mughal Empire to include nearly all of the Indian Subcontinent north of the Godavari river. His power and influence, however, extended over the entire country because of Mughal military, political, cultural, and economic dominance. To unify the vast Mughal state, Akbar established a centralised system of administration throughout his empire and adopted a policy of conciliating conquered rulers through marriage and diplomacy.\r\n\r\nBy abolishing the sectarian tax on non-Muslims and appointing them to high civil and military posts, he was the first Mughal ruler to win the trust and loyalty of the native subjects. He had Sanskrit literature translated, participated in native festivals, realizing that a stable empire depended on the co-operation and good-will of his subjects. Thus, the foundations for a multicultural empire under Mughal rule was laid during his reign. Akbar was succeeded as emperor by his son, Jahangir\r\n\r\nOn 3 October 1605, Akbar fell ill with an attack of dysentery, from which he never recovered. He is believed to have died on or about 27 October 1605, after which his body was buried at a mausoleum in Sikandra, Agra.\r\nSeventy-six years later, in 1691, a group of austere Hindu rebels known as the Jats, rebelling against the Mughal Empire robbed the gold, silver and fine carpets within the tomb, desecrated Akbar''s mausoleum\r\n'),
(4, 'Jahangir', 'Nur-ud-din Mohammad Salim, known by his imperial name Jahangir,(30 August 1569 to 28 October 1627) was the fourth Mughal Emperor who ruled from 1605 until his death in 1627.Jahangir was the eldest surviving son of Mughal Emperor Akbar and was declared successor to his father from an early age. Impatient for power, however, he revolted in 1599 while Akbar was engaged in the Deccan. Jahangir was defeated, but ultimately succeeded his father as Emperor in 1605 due to the immense support and efforts of his step-mothers, Empress Ruqaiya Sultan Begum and Salima Sultan Begum, both of whom wielded great influence over Akbar and favoured Jahangir as his successor\r\n\r\nThe first year of Jahangir''s reign saw a rebellion organized by his eldest son Khusraw. The rebellion was soon put down Khusraw was brought before his father in chains. After subduing and executing nearly 2000 members of the rebellion, he blinded his renegade son of Khusrau.\r\n\r\nHe was trying to restore it by visiting Kashmir and Kabul. He went from Kabul to Kashmir but returned to Lahore on account of a severe cold\r\n\r\nJahangir died on the way back from Kashmir near Sarai Saadabad in 1627. To preserve his body, the entrails were removed and buried in the Chingus Fort, Kashmir. The body was then transferred to Lahore to be buried in Shahdara Bagh, a suburb of Lahore, Punjab. He was succeeded by his third son, Prince Khurram who took the title of Shah Jahan. Jahangir''s elegant mausoleum is located in the Shahdara locale of Lahore and is a popular tourist attraction in Lahore\r\n'),
(5, 'Shah Jahan', 'A''la Azad Abul Muzaffar Shahab ud-Din Mohammad Khurram (January 5, 1592 to February 1, 1666) better known by his imperial name Shah Jahan, was the fifth Mughal Emperor who reigned from 1628 until 1658. While young, Khurram was the favourite of his legendary grandfather, the third Mughal emperor Akbar the Great.\r\n\r\nAt a young age, he was chosen as successor to the Mughal throne after the death of his father, Emperor Jahangir, in 1627. He is considered one of the greatest Mughals. His reign has been called the Golden Age of the Mughals and one of the most prosperous ages of Indian civilization. Like Akbar, he was eager to expand his vast empire. In 1658, he fell ill and was confined by his son Emperor Aurangzeb in Agra Fort until his death in 1666.\r\n\r\nThe period of his reign was the golden age of Mughal architecture. Shah Jahan erected many splendid monuments, the most famous of which is the Taj Mahal at Agra, built in 1632-1648 as a tomb for his beloved wife, Empress Mumtaz Mahal.\r\n'),
(6, 'Aurangzeb', 'Abul Muzaffar Muhi-ud-Din Mohammad Aurangzeb, (4 November 1618 - 3 March 1707) commonly known as Aurangzeb and by his imperial title Alamgir ("world-seizer or universe-seizer") was the sixth Mughal Emperor and ruled over most of the Indian subcontinent. His reign lasted for 49 years from 1658 until his death in 1707. Aurangzeb was a notable expansionist and during his reign, the Mughal Empire reached its greatest extent\r\n\r\nHe was among the wealthiest of the Mughal rulers with an annual yearly tribute of $38,624,680 (in 1690). He was a pious Muslim, and his policies partly abandoned the legacy of Akbar''s secularism, which remains a very controversial aspect of his reign. During his lifetime, victories in the south expanded the Mughal Empire to more than 3.2 million square kilometres and he ruled over a population estimated as being in the range of 100-150 million subjects.\r\n\r\nHe was a strong and effective ruler, but with his death the great period of the Mughal dynasty came to an end, and central control of the sub-continent declined rapidly\r\n\r\nEven when ill and dying, Aurangzeb made sure that the populace knew he was still alive, for if they had thought otherwise then the turmoil of another war of succession was likely. He died in Ahmednagar on 20 February 1707 at the age of 88, having outlived many of his children. His modest open-air grave in Khuldabad expresses his deep devotion to his Islamic beliefs. It is sited in the courtyard of the shrine of the Sufi saint Shaikh Burhan-u''d-din Gharib, who was a disciple of Nizamuddin Auliya of Delhi\r\n	');

-- --------------------------------------------------------

--
-- Table structure for table `slave`
--

CREATE TABLE IF NOT EXISTS `slave` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--
-- Dumping data for table `slave`
--

INSERT INTO `slave` (`id`, `ruler`, `des`) VALUES
(1, 'Qutubuddin Aibak', 'Qutubuddin Aibak (1206-1210 A.D.) was the founder of the Slave Dynasty. He mmenced the building of the Qutub Minar which was later completed by AItamash (1211-1236) who was succeeded by Razia Begum (1236-1239 A.D.) his daughter.\r\n\r\nQutb-ud-din Aibak ruled for four years until he had a fatal accident while playing chaugan (polo). His horse fell and he was impaled on the pommel of his saddle. His early death prevented him completing his plans for organizing his kingdom and establishing a sound administration. He built the Quwwat-ul-Islam mosque in Delhi\r\n\r\nHe started the construction of Qutb Minar in Delhi, which is dedicated to a famous Sufi Saint of the time, Qutbuddin Bakhtiar Kaki. After he died, the minar was completed by his successor, Iltutmish. He is also remembered as lakhbaksh or giver of lakhs, because of his generosity.\r\n	'),
(2, 'Aram Shah', 'Aram Shah (probably reigned 1210 to 1211) was the second sultan of the Mamluk Sultanate (Slave Dynasty).The relationship of Aram with Qutb-ud-din Aibak (1206 to 1210) is a subject of controversy. According to some, he was Aibak''s son, but Minhaj-us-Siraj distinctly writes that Qutb-ud-din only had three daughters. Abul Fazl has made the "astonishing statement" that he was the Sultan''s brother\r\n\r\nA modern writer has hazarded the opinion that "he was no relation of Qutub-ud-din" but was selected as his successor as he was available on the spot. In fact, there were no fixed rules governing the succession to the Crown in the Turkish State. It was determined largely by the exigencies of the moment and the influence of the Chihalgani or ''Corp of Forty''. The Chihalgani, who were the administrative and military elite of the Ilbari tribe, crowned him king thinking that he would be able to deal with the problems facing the Sultanate\r\n\r\nAram was ill-qualified to govern a kingdom. The Chihalgani soon conspired against him and invited Shams-ud-din Iltutmish, then Governor of Badaun, to replace Aram. Iltutmish responded to their call, and, advancing with his entire army, defeated Aram on the plain of Jud near Delhi in 1211. What became of Aram is not quite certain.\r\n	'),
(3, 'Iltutmish', 'Shams-ud-din Iltutmish (AlTaMash/Iltutmish)(r. 1211 to 1236) was the third ruler of the Mamluk dynasty of Delhi of Turkic origin.He was a slave of Qutb-ud-din Aibak and later became his son-in-law and close lieutenant. He was the Governor of Badaun when he deposed Qutub-ud-din''s successor Aram Shah and acceeded to the throne of the Delhi Sultanate in 1211\r\n\r\nHe shifted Capital from Lahore to Delhi, remained the ruler until his death on May 1, 1236.Iltutmish introduced the silver tanka and the copper jital-the two basic coins of the Sultanate period, with a standard weight of 175 grains. He introudced Iqtadari system: division of empire into Iqtas, which were assigned to the nobles and officers in lieu of salary.\r\n\r\nHe built the Hauz-i-Shamsi reservoir in Mehrauli in 1230, which also has Jahaz Mahal standing on its edge, used by later Mughal Emperors. In 1231, he built Sultan Ghari the mausoleum of his eldest son, Prince Nasiru''d-Din Mahmud, which was the first Islamic Mausoleum in Delhi. His own tomb exists, within the Qutb complex in Mehrauli, Delhi.\r\n\r\nHe suppressed all internal revolts and also checked external invaders successfully. He got completed the construction of qutub minar.\r\n'),
(4, 'Razia Sultana', 'Raziyya al-Din (1205 to October 13, 1240)  throne name Jalalat ud-Din Raziya usually referred to in history as Razia Sultan, was the Sultan of Delhi in India from 1236 to May 1240. Like some other Muslim princesses of the time, she was trained to lead armies and administer kingdoms if necessary\r\n\r\nRazia Sultana was the only woman ruler of both the Sultanate and the Mughal period, although other women ruled from behind the scenes.Razia refused to be addressed as Sultana because it meant "wife or mistress of a sultan". She would answer only to the title "Sultan". Razia had all qualities of a great monarch\r\n\r\nazia is said to have pointed out that the spirit of religion was more important than its parts, and that even the Islamic prophet Muhammad spoke against overburdening the non-Muslims. On another occasion, she reportedly tried to appoint an Indian Muslim convert from Hinduism to an official position but again ran into opposition from the nobles.\r\n\r\nBeing the first female monarch of the Delhi Sultanate, Razia Sultan has been the subject of many legends. A piece of historical fiction entitled ''Razia: Queen of India'' based on the Sultana''s life written by Rafiq Zakaria in 2000. The Sultana also has her own title in the Indian comic book series, Amar Chitra Katha. More recently, she was the subject of Razia Sultan, a 1983 urdu film, written and directed by Kamal Amrohi, starring Hema Malini as Razia and Dharmendra as Jamal-ud-Din Yaqut.\r\n'),
(5, 'Nasir ud din Mahmud', 'Nasir ud din Mahmud, Nasir ud din Firuz Shah (1246 to 1266) was the eighth sultan of the Mamluk Sultanate (Slave dynasty). He was the son of Nasiruddin Mahmud(died 1229), who was the youngest son of Shams ud din Iltutmish (1211 to 1236). \r\n\r\nHe was named after his father, by Shams ud din Iltutmish, for he had grown an intense filial attachment, to the only begot son of his posthumous child. He succeeded Ala ud din Masud after the chiefs replaced Masud when they felt that he began to behave as a tyrant.\r\n\r\nAs a ruler, Mahmud was known to be very religious, spending most of his time in prayer and renowned for aiding the poor and the distressed. However, it was actually his Deputy Sultan or Naib, Ghiyas ud din Balban, who primarily dealt with the state affairs. After Mahmud''s death in 1266, Balban (1266 to 1287) rose to power as Mahmud had no children to be his heir.\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `sur`
--

CREATE TABLE IF NOT EXISTS `sur` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ruler` text NOT NULL,
  `des` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--
-- Dumping data for table `sur`
--

INSERT INTO `sur` (`id`, `ruler`, `des`) VALUES
(1, 'Sher Shah Suri', 'Sher Shah Suri (1486 to 22 May 1545) ( Farid Xan Ser Sah Suri, birth name Farid Khan, also known as Sher Khan, "The Lion King") was the founder of the Sur Empire in North India, with its capital at Delhi.An ethnic Pashtun, Sher Shah took control of the Mughal Empire in 1540.\r\n\r\nSher Khan overran the state of Bengal and established the Sur dynasty.A brilliant strategist, Sher Shah proved himself a gifted administrator as well as an able general. His reorganization of the empire laid the foundations for the later Mughal emperors, notably Akbar the Great, son of Humayun\r\n	\r\nDuring his five year rule from 1540 to 1545, he set up a new civic and military administration, issued the first Rupee and re-organised the postal system of India.He further developed Humayun''s Dina-panah city and named it Shergarh and revived the historical city of Pataliputra as Patna which had been in decline since the 7th century CE.He is also famously remembered for killing a fully grown tiger with his bare hands in a jungle of Bihar. He extended the Grand Trunk Road from Chittagong in Bangladesh to Kabul in Afghanistan.\r\n'),
(2, 'Islam Shah Suri', 'Islam Shah Suri (reigned: 1545 to 1554) was the second ruler of the Sur dynasty which ruled part of India in the mid-16th century. His original name was Jalal Khan and he was the second son of Sher Shah Suri.\r\n\r\nOn his father''s death, an emergency meeting of nobles chose Jalal Khan to be successor instead of his elder brother Adil Khan, since he had shown greater military ability. Jalal Khan was crowned on 26 May 1545 and took the title "Islam Shah". He was still worried that his brother would threaten his power and tried to have him captured. But Adil Khan evaded his grasp and raised an army. It marched on Islam Shah while he was at Agra. In the battle Islam Shah came out victorious and Adil Khan fled, never to be seen again.\r\n\r\nIslam Shah died on 22 November 1554. He was succeeded by his son Firuz Shah Suri, who was only twelve. Within a few days the boy ruler had been murdered by Sher Shah''s nephew Muhammad Mubariz Khan, who then ascended the throne as Muhammad Adil Shah.\r\n'),
(3, 'Ibrahim Shah Suri', 'Ibrahim Shah Suri was the fifth ruler of Sur dynasty, a Pashtun (Afghan) dynasty of late medieval northern India.\r\n\r\nIbrahim Khan Suri was son of Ghazi Khan. He was the brother-in-law of sultan Muhammad Adil Shah. He was the governor of Agra in 1555, when he revolted against the sultan. Adil Shah despatched his army to crush the revolt, but he defeated Adil''s army and marched towards Delhi. After capturing Delhi, he assumed the regal title and became Ibrahim Shah Suri. But in the same year, Sikandar Shah Suri defeated him at Farah, 32 km from Agra in spite of the numerical superiority of Ibrahim''s army. Sikandar took possession of both Delhi and Agra\r\n\r\nAfter losing Delhi and Agra, Ibrahim began his strife with Adil Shah. But he was defeated by Adil''s army led by his wazir Hemu twice, first near Kalpi and next near Khanua. He took refuge in the fort of Bayana, but it was besieged by Hemu''s army. He got some respite when Hemu was recalled by Adil. Later, Ibrahim took refuge in Orissa, where he died in 1567-68.\r\n'),
(4, 'Sikandar Shah Suri', 'Sikandar Shah Suri (died 1559) was the sixth ruler of Sur dynasty, a late medieval Pashtun (Afghan) dynasty of northern India. He became the sultan of Delhi after overthrowing Ibrahim Shah Suri.\r\n\r\nSikandar Shah Suri''s actual name was Ahmad Khan Suri. He was the brother-in-law of sultan Muhammad Adil Shah. He was the governor of Lahore before declaring independence from Delhi in 1555\r\n\r\nAfter becoming the independent sultan and bringing Punjab under control, he marched towards the territory controlled by sultan Ibrahim Shah Suri. Ibrahim was defeated in a battle at Farah near Agra and Sikandar took possession of both Delhi and Agra. While Sikandar was busy with his struggle against Ibrahim, Humayun captured Lahore in February 1555. Another detachment of his forces captured Dipalpur. Next, the Mughal army occupied Jalandhar and their advanced division proceeded towards Sirhind. Sikandar sent a force of 30,000 horses but they were defeated by the Mughal army in a battle at Machhiwara and Sirhind was occupied by the Mughals. Sikandar, then led an army of 80,000 horses himself and met the Army at Sirhind. On June 22, 1555 he was defeated by the Mughal army and was compelled to retreat to the Sivalik Hills in northern Punjab. The victorious Mughals marched to Delhi and occupied it.\r\n\r\nBairam Khan sent Khan Alam (Iskandar Khan) to assist Khizr Khwaja Khan and finally on December 7, 1556 Akbar along with Bairam Khan left Delhi to deal with him. Sikandar again retreated to the Sivaliks and took refuge in the fort of Mankot. Bairam Khan besieged the fort. After six months of resistance, Sikandar surrendered the fort on July 25, 1557.He received an assignment in Bihar but expelled by Akbar within a short period. He died in Bengal in 155\r\n		'),
(5, 'Adil Shah Suri', 'Adil Shah Suri was the seventh and final ruler of the Sur dynasty. He was the brother of Sikandar Shah Suri, who ruled over a region east of Delhi after Sikandar Shah Suri was defeated by Humayun in 1555. He and Sikandar Shah Suri were contenders for the Delhi throne against the Mughal emperor Akbar the Great\r\n\r\nEarly in Adil Shah''s reign, he fought back a challenge from Muhammad Shah, ruler of Bengal. At the battle of Chhapparghatta in December 1555, Adil Shah and his Hindu general Hemu Hemachandra Bhargava routed the Bengal forces and the Muhammad Shah was killed. The following year, following the child-Emperor Akbar''s absence from Delhi on a campaign, Hemu attacked and defeated the regent Tardi Beg Khan who fled the city. This was Hemu''s 22nd successive victory in battle and rather than appoint Adil Shah as ruler he appointed himself ruler.\r\n\r\nthe Bengal throne had passed on to Ghiyasuddin Abul Muzaffar Bahadur Shah, son of the slain Muhammad Shah. After killing an ambitious uncle, Bahadur Shah marched against Adil Shah to avenge his father''s murder. In the battle of Fathpur in Munghyr in April 1557 AD Adil Shah''s army was routed and Adil himself was captured and killed.\r\n');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
